# Generated by Django 2.2 on 2019-05-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classb', models.CharField(max_length=30)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Classify')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('eml', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('activate', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goodsimg')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=30)),
                ('discount', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=10)),
                ('describe', models.CharField(max_length=150)),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Classify')),
            ],
        ),
    ]
